### ISSUE TITLE
VS Studio can not find the build task

### ISSUE THREAD

**Issue by TBCode523** [xsahil03x/super_enum#24]
VS Studio for some reason is not detecting the build task runner. Could be something wrong with the library or my version of VS Studio(I updated to the latest version)?

**Comment by xsahil03x** [comment]
Hey, can you post the full log please?

**Comment by TBCode523** [comment]
I'm kind of new at this. I don't know what you mean by the full log, however I explained my problem in more depth with pictures on stackoverflow.
[https://stackoverflow.com/questions/59462514/build-runner-is-not-found-in-vs-studio](url)

**Comment by xsahil03x** [comment]
I don't think the URL is working but to my understanding, there isn't any issue with the package.

**Comment by TBCode523** [comment]
Where is the URL located and how can I access it? Sorry if it's a trivial problem since this is the 1st issue I had with super enums.
