### ISSUE TITLE
Use external class directly without wrapping

### ISSUE THREAD

**Issue by passsy** [xsahil03x/super_enum#29]
Sometimes I share classes between multiple superEnums. This is currently only possible by wrapping them each time I use them.

```dart
class ApiError { /*...*/ }

@superEnum
enum _ResultA {
  @Data(fields: [
    DataField('error', ApiError),
  ])
  Error,
}

@superEnum
enum _ResultB {
  @Data(fields: [
    DataField('error', ApiError),
  ])
  Error,
}
```

I'd prefer to use some classes directly without having them auto-generated and wrapped.

```dart
class ApiError { /*...*/ }

@superEnum
enum _ResultA {
  @UserClass(ApiError)
  Error,
}

@superEnum
enum _ResultB {
  @UserClass(ApiError)
  Error,
}
```

**Comment by astralstriker** [comment]
I will check the feasibility of this and get back to you. Can you suggest a usecase for this feature? I can't really think of one

**Comment by astralstriker** [comment]
Office work has rendered us unable work on other projects these days. It will remain the same for the next few days as well. Would you like to implement this feature, if this is feasible in the first place, and submit a pull request?
