### ISSUE TITLE
Enum as data field in another enum

### ISSUE THREAD

**Issue by fdietze** [xsahil03x/super_enum#37]
I'm trying to do this:
```dart
@superEnum
enum _SelectedContact {
  @Data(fields: [DataField('user', User)])
  InternalUser,

  @Data(fields: [DataField('contact', Contact)])
  AddressBook,
}
```

Where Contact is another super enum defined in a different file. When building this, the generated file only contains the following comment, and no code:

```dart
/*FormatException: Not an instance of Type.*/
```

Is reusing enums in other enums not allowed?

**Comment by passsy** [comment]
I ran myself into this problem as well. It's currently not supported but it could be in the future.

One way to solve this is to use the `@UseClass` annotation and create the classes yourself
