### ISSUE TITLE
DataFields with a name including 'T' break code generation

### ISSUE THREAD

**Issue by WanderingFire2001** [xsahil03x/super_enum#39]
Latest update (0.4.0, released several hours ago) has a very bad bug.

Any data field with a capital 'T' in the name appears to break code generation, yielding the standard comment header and the single line:
```/*State must be annotated with @generic*/```

To reproduce:

The following works properly -- exactly as you would expect:
```dart
import 'package:super_enum/super_enum.dart';

part 'super_enum_sample.g.dart';

class SomeVee {
  String data;
}

@superEnum
enum _StatesGood {
  @Data(fields: [
    DataField<SomeVee>('fieldName'),
  ])
  State
}
```
The following fails, and is the same other than the type of field, now being Some**T**ee instead of Some**V**ee (T in the name vs no T in the name).

```dart
import 'package:super_enum/super_enum.dart';

part 'super_enum_sample.g.dart';

class SomeTee {
  String data;
}

@superEnum
enum _StatesBad {
  @Data(fields: [
    DataField<SomeTee>('fieldName'),
  ])
  State
}
```

The problem stems from line 377 of [class_generator.dart](https://github.com/xsahil03x/super_enum/blob/master/super_enum_generator/lib/src/class_generator.dart#L377)
```dart
    if (_classFields
        .any((e) => type_processor.dataFieldType(e).contains('T'))) {
      if (!isGeneric) {
        throw InvalidGenerationSourceError(
            '${field.name} must be annotated with @generic');
      }
    }
```
(Hairy debug session to find this... 'my T' was in a complex type using built values and I had a lot of suspicions to track down before I got to "does it include a capital T' ;-)

Love all the new features, thanks for all your hard work!

**Comment by astralstriker** [comment]
That's a very bad bug indeed. Thanks for letting us know. Will fix this on an urgent basis.
