### ISSUE TITLE
@UseClass generating Error

### ISSUE THREAD

**Issue by dennis-szymanski** [xsahil03x/super_enum#42]
Hey guys,

I just ran into another code generation error.
When using the same Class in @UseClass() the build_runner generates the wrapper twice.

For example this:
```
@superEnum
enum _RevenueState {
  @object
  Empty,
  @UseClass(RevenueLoaded)
  YearLoaded,
  @UseClass(RevenueLoaded)
  MonthLoaded,
  @Data(fields: [DataField<String>('message')])
  Error,
}
class RevenueLoaded {
  final Revenue revenue;
  const RevenueLoaded({
    @required this.revenue,
  });
}
```

Generates the RevenueLoadedwWrapper twice

Have a nice day !

**Comment by passsy** [comment]
Great catch, I'm on it
