### ISSUE TITLE
Why renaming enum fields?

### ISSUE THREAD

**Issue by olehmisar** [xsahil03x/super_enum#50]
Why does the generator rename enum fields? For example, if I define the following `enum`

```dart
@superEnum
enum _Result {
  @object
  Success,

  @object
  Error
}
```

...`Success` becomes `success` and `Error` becomes `error`. Is there a reason for this? I think it would be better to keep the original names to avoid confusion.

**Comment by shinayser** [comment]
Agreed!

**Comment by xsahil03x** [comment]
That's how we generally write `named` / `factory` constructors in dart
https://dart.dev/guides/language/language-tour#constructors
