### ISSUE TITLE
emit `when` method arguments for "empty" actions

### ISSUE THREAD

**Issue by ened** [xsahil03x/super_enum#52]
Given I have a super_enum definition like this:

```
@superEnum
enum _ContactUsAction {
  CallPhone,
  StartLiveChat
}
```

Then the generated when method looks like this:

```
  R when<R>(
      {@required
          FutureOr<R> Function(CallPhone) callPhone,
      @required
          FutureOr<R> Function(StartLiveChat) startLiveChat}) {

...
```

could this possibly be simplified to:

```
  R when<R>(
      {@required
          FutureOr<R> Function() callPhone,
      @required
          FutureOr<R> Function() startLiveChat}) {

...
```

As from my point of view, the event has no associated values and thus does not need to be passed into the when method.

**Comment by xsahil03x** [comment]
Yes, it can be done. @astralstriker what are your views on this?

**Comment by astralstriker** [comment]
@ened @xsahil03x yes looks redundant to me too, we should remove them.
