### ISSUE TITLE
WhenPartial breaks when updraging from 0.3.0 to 0.4.2

### ISSUE THREAD

**Issue by shadracktaeli** [xsahil03x/super_enum#60]
so i'm getting these weird errors because i use `whenPartial` in my bloc's `mapEventToState`. 

```dart
yield* event.whenPartial(
  someEvent: (_) async* {
     // some logic
     return State.someState();
  }
);
```
not sure why it's not working anymore

**Comment by astralstriker** [comment]
Please share the error/exception log.

**Comment by xsahil03x** [comment]
Closing as no response.
