### ISSUE TITLE
super_enum is not working with analyzer ^0.40.1 

### ISSUE THREAD

**Issue by SaeedMasoumi** [xsahil03x/super_enum#63]
The current version of super enum will not work with dart 2.10, analyzer 0.40.1, and build_runner 2.10.3 because there is a breaking change on `usedClass.toTypeValue().getDisplayString()` API which needs the `withNullability` to pass.

Also, overriding analyzer version will not help.

Related Issues:
 - https://github.com/flutter/flutter/issues/62240
 - https://github.com/hivedb/hive/issues/387
 - https://github.com/flutter/flutter/issues/63556

**Comment by NikitaMasev** [comment]
The same issue. Other packages already works with analyzer ^0.40.4, but super_enum_generator 0.5.0 depends on analyzer ^0.39.2.

**Comment by xsahil03x** [comment]
Fixed in #64, will release soon.
